### ISSUE TITLE
Hi Nils, need any help?

### ISSUE THREAD

**Issue by chrisma** [djnilse/rails-exercise-16#1]
Hi Nils,

we noticed you haven't connected your repo to Travis CI and haven't made any commits yet.
Do you need help with anything?
We'd be happy to assist you if there are any problems.
You can reply to this issue or join us on Slack.

Best,
Christoph

**Comment by djnilse** [comment]
Hey, thanks for the quick help proposal.
I did not yet find the time to start working on the exercise, only cloned it and I did set up Travis for the repo, which now resulted in the first error.
I am looking forward to start working on it.

**Comment by chrisma** [comment]
Alright, good luck.
Reach out if you have issues.
